### PR TITLE
Ta1 Forever Loop Assignment #1: Sourcing Data from the PubMed API

### PR DESCRIPTION
**Pull request by haranku16**
### Team Details
**Team Name:** Forever Loop
**Team Members:** Santosh Ganesan, Haran Nallasivan
**Topic:** PubMed API

### Description
We are sourcing data from the PubMed API to explore research interest into Polio over a time range spanning 3 years before and after discovery of the vaccine in 1957.

### Requirements
No new requirements. Pre-existing requirements:
```
numpy==1.24.3
pandas==2.0.3
matplotlib==3.7.1
seaborn==0.12.2
plotly==5.13.1
selenium==4.10.0
requests==2.31.0
beautifulsoup4==4.12.2
imbalanced-learn==0.11.0
scikit-learn==1.2.2
statsmodels==0.14.0
transformers==4.31.0
```

#### Create your virtual environment
```
python -m venv .venv
```

#### Activate your virtual environment
Mac/Linux (running locally) or Codespaces:
```
source .venv/bin/activate
```

Windows:
```
.venv/Scripts/activate
```

#### Install requirements
```
python -m pip install -r requirements.txt
```

#### Run the script
```
python api_pubmed.py
```

Example of running the script with different arguments **(optional)**:
```
python api_pubmed.py --disease influenza --start 2024 --end 2025
```

Please note that if you're running the script for the first time, the matplotlib dependency will take a few minutes to cache resources like the font library.

### Demo Video
https://drive.google.com/file/d/1F8ZHucchKD_Z8vH2C_M-IM-T1RsAEqBc/view?usp=sharing

### CODE REVIEW

**Comment by tejasj02** [comment]
code ran well! could add venv implementation for codespaces

**Comment by haranku16** [comment]
> code ran well! could add venv implementation for codespaces

Thanks for the callout. I've updated the PR description accordingly.

**Comment by brinnaebent** [comment]
Video 15/15 - Really nice example use case!

**Review by mhy-666 — COMMENTED** [review]
Looks great!
Clear function and code structure!

**Pull request merged**
