### PR TITLE
TA7 HKBoyz

### PR DESCRIPTION
**Pull request by choonghwanlee**
Team members: Andrew Jin & Jason Lee

This repository puts together a code demo for feature engineering using OpenCV. The main script 'opencv_demo.py' uses OpenCV image processing functions to process images of the human eye and detect the pupil's center and radius. 

## Requirements

To run the code, we need to additionally install the most recent version of OpenCV (i.e. pip install opencv-python) and PIL (i.e. pip install pillow)

pillow==10.4.0
opencv-python==4.10.0.84. 

## Usage

Run the code using `python opencv_demo.py`. This generates an output file `output.jpg` that is structured as follows:

1. The first image in each row is the original input image
2. The second image in each row is the binary mask we extract from OpenCV feature engineering
3. The third image in each row shows the predicted center and radius overlayed on the original input image

We use 3 sample images of the human eye from the internet

### CODE REVIEW

**Comment by mhy-666** [comment]
Please remove extra files in the 'files changed' section.

**Comment by choonghwanlee** [comment]
Hi @mhy-666, the instructions on Canvas say adding sample data manually to /data is permitted for this assignment: "For your example, use a built-in dataset if possible or a dataset that can be accessed through a python library. If not possible, add sample data to the data/ repository." 

The code runs on these sample images. Do I still remove the extra files?

**Comment by choonghwanlee** [comment]
Hi @mhy-666, as we discussed during class yesterday, I edited the PR to import images from online URLs instead of from the /data directory. Now, there is only 1 file changed in the PR. Thanks, Jason

**Comment by mhy-666** [comment]
Nice code and clear instructions!

**Pull request merged**
