### PR TITLE
TA7: Aditya Raju and Mariam Khan

### PR DESCRIPTION
**Pull request by adityaraju926**
Sentiment Analysis using NLTK done on a twitter dataset about the soccer player Cristiano Ronaldo

### CODE REVIEW

**Comment by brinnaebent** [comment]
Please remove all files except for the single script so we can merge. Thanks! Add additional requirements to text of PR.

**Comment by Mkhan13** [comment]
@brinnaebent Deleted all files except for nlkt.py

**Requirements:**
pandas==2.0.3
nltk==3.8.1

**Comment by brinnaebent** [comment]
@adityaraju926 @Mkhan13 You have PR'ed into the wrong branch. Please make a new PR into the correct branch and delete this PR.

**Comment by adityaraju926** [comment]
@brinnaebent I switched the base branch so it should be pointing to the right one now

**Pull request closed without merging**
