### PR TITLE
TA5 - Trackstars

### PR DESCRIPTION
**Pull request by auto-d**
This PR contains a Streamlit app demonstrating Bayes theorem, which has concurrently been deployed to https://bayes-explainer.streamlit.app/. 

The `requirements.txt` file has not been modified, but the following dependencies on the app exist: 
```
numpy==2.1.2
pandas==2.2.3
matplotlib==3.9.1
plotly==5.13.1
streamlit==1.39.0
```

The application requires local copies of rainfall and river crest data that are included in a resource subdirectory.

### CODE REVIEW

**Comment by mhy-666** [comment]
Please remove extra files to make sure there is only one file in your PR(which means you can only see one file in the 'files changed' section)

**Comment by auto-d** [comment]
@mhy-666, the two additional files are the raw data which drive the statistical analysis and are essential to the demonstration.

**Comment by auto-d** [comment]
@mhy-666, I migrated the CSV content to Azure blob storage and revised the streamlit app to pull it down at deploy time.

**Comment by mhy-666** [comment]
Looks great! Nice code!

**Pull request merged**
