### PR TITLE
TA1: Use the USGS Earthquake Hazards Program API

### PR DESCRIPTION
**Pull request by mwilliams31**
### Assignment Details
- Completed individually by Matt Williams
- [API documentation](https://earthquake.usgs.gov/fdsnws/event/1/) (no API key required)
- Script name: `api_earthquake.py`
- Demo video link: https://warpwire.duke.edu/w/nXQIAA/

### Dependencies
  - Additional library: [`pgeocode==0.5.0`](https://pypi.org/project/pgeocode/)
  - The script uses the built-in [`dataclasses`](https://docs.python.org/3/library/dataclasses.html) library, which requires Python 3.7+.

### README.md
`api_earthquake.py` retrieves earthquake data from the USGS Earthquake Hazards Program API (https://earthquake.usgs.gov/fdsnws/event/1/) based on a provided zipcode and search parameters. Search parameters include the radius, start date, end date, minimum magnitude, and maximum magnitude. Earthquake data returned by the query is distilled into desired information and printed to the console.

**Usage**:
```
api_earthquake.py -h
usage: api_earthquake.py [-h] [--radius RADIUS] [--startdate STARTDATE] [--enddate ENDDATE] [--minmagnitude MINMAGNITUDE] [--maxmagnitude MAXMAGNITUDE] zipcode

Display earthquake data based on a location and search parameters

positional arguments:
  zipcode               Zipcode of the location to search for earthquakes

options:
  -h, --help            show this help message and exit
  --radius RADIUS       Radius in kilometers to search for earthquakes; default is 300 km
  --startdate STARTDATE
                        Start date of the search in the format YYYY-MM-DD; default is 30 days ago
  --enddate ENDDATE     End date of the search in the format YYYY-MM-DD; default is today
  --minmagnitude MINMAGNITUDE
                        Minimum magnitude of the earthquake (e.g., 2.5)
  --maxmagnitude MAXMAGNITUDE
                        Maximum magnitude of the earthquake (e.g., 5.4)
```
**Example**:
```
$ python api_earthquake.py 29401 --radius 200 --startdate 2024-01-01 --enddate 2024-06-01 --minmagnitude 2 --maxmagnitude 2.2
Found 2 earthquakes

6 km ESE of Elgin, South Carolina
        Magnitude: 2.16
        Time: 2024-03-27 05:46:07 UTC
        Location: 34.1488333333333, -80.728
        Depth: 2.2 km
6 km E of Elgin, South Carolina
        Magnitude: 2.19
        Time: 2024-03-24 07:22:20 UTC
        Location: 34.1611666666667, -80.7261666666667
        Depth: 2.92 km
```

### CODE REVIEW

**Comment by brinnaebent** [comment]
Hi @mwilliams31 - please revert changes to the README and requirements.txt in git. Place the text of your README + additional requirements here in your PR. (This helps us avoid merge conflicts!) You should have 1 file changed.

How to revert:

git checkout YOUR_BRANCH_NAME

git checkout data-sourcing-ta1 -- README.md

git add README.md

git commit -m "Revert changes to README"

git push

**Comment by brinnaebent** [comment]
Thanks for the demo video, Matt. Video 15/15

**Comment by mwilliams31** [comment]
`requirements.txt` change removed and `README.md` text added to the PR comment above.

> You should have 1 file changed.

@brinnaebent Do I need to remove my `test_api_earthquake.py` as well?

**Comment by brinnaebent** [comment]
@mwilliams31 that would be great - if you could remove the test files for the final commit, that will make merging into one repo easier. Thanks!

**Comment by brinnaebent** [comment]
Code 30/30. Code is well documented and meets all requirements.

**Pull request merged**
