### PR TITLE
Ta1 Matana P (World Bank API)

### PR DESCRIPTION
**Pull request by beungz**
**Team Assignment 1**
**World Bank API**
**Team: Matana Pornluanprasert (Matana P)**

This is a Python script that can request GDP data from World Bank API, print resulting table, draw horizontal bar chart, and save the result as CSV.

Requirements:
numpy==2.1.0
pandas==2.2.2
matplotlib==3.9.2
requests==2.31.0
argparse==1.4.0
pytest==8.3.2

Demo Video Link: [Google Drive](https://drive.google.com/file/d/1YDeH0KZSP2q6WnrhXsc6r1b_bSsYDc3R/view?usp=sharing)

### CODE REVIEW

**Comment by brinnaebent** [comment]
Hi @beungz  - please revert changes to the README and requirements.txt in git. Place the text of your README + additional requirements here in your PR. (This helps us avoid merge conflicts!) You should have 1 file changed.

How to revert:

git checkout YOUR_BRANCH_NAME

git checkout data-sourcing-ta1 -- README.md

git add README.md

git commit -m "Revert changes to README"

git push

**Comment by beungz** [comment]
Hi  Dr.Brinnae @brinnaebent,

I just reverted the changes in README and requirements.

My additional requirements are:
argparse==1.4.0
pytest==8.3.2

I have used newer versions of numpy, pandas, and matplotlib, 
numpy==2.1.0
pandas==2.2.2
matplotlib==3.9.2
but I believe that the versions stated in original requirements.txt should also work.

Thank you!

----------------------------------------------------------------------

# Team Assignment #1
## Data Sourcing
World Bank API

This is a Python script that can request GDP data from World Bank API, print resulting table, draw horizontal bar chart, and save the result as CSV.

## Installation

1. Install all dependencies
```
pip install -r requirements.txt
```

2. To run the code, type the followings in the terminal

On Windows:
```
py api_world_bank.py --year <YEAR> --top <TOP> --gdptype <TYPE>
```

On other systems:
```
python api_world_bank.py --year <YEAR> --top <TOP> --gdptype <TYPE>
```
where   
`<YEAR>` is the input year for the GDP data [default = 2023]

`<TOP>` is number of top countries to show in the GDP chart (top largest) [default = 10]

`<TYPE>` can be either 0, 1, or 2 [default = 0]
- 0: GDP, Current USD
- 1: GDP per capita, Current USD
- 2: GDP Growth, Constant Local Currency

For example, to get top `5` largest economies in `2020` by `GDP`:
```
py api_world_bank.py --year 2020 --top 5 --gdptype 0
```
You should see output like this:
```
  country_id    country_name             gdp_value
1         US   United States        21322950000000
2         CN           China        14687744162801
3         JP           Japan  5055587093501.589844
4         DE         Germany  3887727161914.410156
5         GB  United Kingdom  2697806592293.859863
```
The horizontal bar chart should pop up automatically


## Unit Test
Run `pytest`
```
pytest api_world_bank.py
```
This will run 4 test functions in api_world_bank.py

**Comment by brinnaebent** [comment]
Video 15/15. Well explained, very clear.

**Comment by brinnaebent** [comment]
Code 30/30. Clear and well documented. Appreciate the great documentation on how to run the code, that made it very easy to use.

**Pull request merged**
