### PR TITLE
Team Assignment #1 Submission - Team MIA

### PR DESCRIPTION
**Pull request by laxman-22**
This PR is Team MIA's submission to Team Assignment 1.

Team MIA:
Aryan Laxman Sirohi
Ashley Xu
Yash Hegde

* The script can be ran by following the instructions in the README file.
* The video link for the code walkthrough and demo can be found [here](https://youtu.be/82HdDqLgSVo/)

### CODE REVIEW

**Comment by laxman-22** [comment]
# Team MIA Assignment #1

### Ensure you use Python versions around 3.10 in your virtual environment, as versions around 3.12 may cause issues!

## Installation
1. Clone this repo

```bash
git clone https://github.com/AIPI510/aipi510-fall24.git
```

2. Go into the directory where this repo was cloned
```bash
cd aipi510-fall24
```

3. Checkout the ta1-mia branch to retrieve our team's changes
```bash
git checkout ta1-mia
```

3. Install the required dependencies using the following command
```bash
pip install requirements.txt
```

4. Run the api_opensky.py script and follow instructions in terminal to use the application
```bash
python api_opensky.py
```

## Notes
* Upon running the live tracking web app there may be an error that shows up as follows
```
Traceback (most recent call last):
  File "c:\Users\aryan\Documents\aipi510-fall24\api_opensky.py", line 171, in update_graph
    for state in state_vectors.states:
AttributeError: 'NoneType' object has no attribute 'states'
```
This is expected and simply requires a refresh of the page or waiting a few seconds for the page to automatically update

* The above error may also occur if you try running the different functions too quickly. For example, if you run the top 10 most crowded airspaces function and immediately run another function, this will raise the above error as the API has limits on how often it can be called

**Comment by laxman-22** [comment]
Extra dependencies required:
dash==2.17.1
opensky-api @ git+https://github.com/openskynetwork/opensky-api.git#egg=opensky-api&subdirectory=python

**Comment by brinnaebent** [comment]
Video 15/15 love the map visualizations!

**Review by medinardaniel — COMMENTED** [review]
Clean, well-commented code. Good job using docstrings. 30/30

**Pull request merged**
