### PR TITLE
Ta1 data miners - Owais and Rajiv - NPS_API

### PR DESCRIPTION
**Pull request by owais-kamdar**
Rajiv and I used the NPS_API for our assignment. We updated the requirements.txt file in our branch to include all necessary dependancies. We first obtained an API to key to pull the data. Afterwards created references for state codes, and activities. Then we used functions to manipulate the data using state codes, and activity filters. To ease user interaction, we made a small portion of the script to help with user interface in the terminal.

https://www.youtube.com/watch?v=eSs_9lKajGc

### CODE REVIEW

**Comment by owais-kamdar** [comment]
National Parks Explorer
This project provides a Python script to explore data from the National Park Service (NPS) API. It allows users to list parks in specific states, find the top states with the most parks offering specific activities, and list parks in a specific state with an activity filter.

Features
Fetch available activities from the NPS API.
List all parks in a specific state with full name and address.
Find the top N states with the most parks offering specific activities.
Display parks in a given state with an activity filter.
Interactive User prompts in terminal for data exploration.

Installation
Clone the repository:
git clone --branch ta1-data-miners https://github.com/AIPI510/aipi510-fall24.git
cd aipi510-fall24

Create a virtual environment:
python3 -m venv venv
source venv/bin/activate

Install the required dependencies:
pip install -r requirements.txt

Usage
Run the script using Python:
python api_nps.py

Follow instructions as prompted in the terminal, following guidelines for field inputs.


Requirements.txt

pip install certifi==2024.8.30 charset-normalizer==3.3.2 Cython==3.0.11 idna==3.8 numpy==2.1.0 pandas==2.2.2 pybind11==2.13.5 python-dateutil==2.9.0.post0 pytz==2024.1 requests==2.32.3 setuptools==68.0.0 six==1.16.0 tzdata==2024.1 urllib3==2.2.2 wheel==0.44.0

**Comment by notthattal** [comment]
Code ran as expected and the instructions were easy to understand

**Comment by brinnaebent** [comment]
Video 15/15. I would use this! Super fun, love the interactivity.

**Review by medinardaniel — COMMENTED** [review]
Clean, well-commented code. 30/30
Refrain from committing api keys in the future.

**Pull request merged**
