### PR TITLE
Ta1 hkboyz

### PR DESCRIPTION
**Pull request by andrewcxjin**
Team Assignment 1 for Jason Lee and Andrew Jin - Web Scraping using Requests

No additional requirements needed other than those listed in requirements.txt

[Link to video:](https://youtu.be/9GvhQAU-Wgs)
Note: This was done through a Zoom meeting as both team members were in recovery from illness at the time of recording

API key: d6yqmeTangz25ECiWcXaEX0s2VMnMg3zzcZ4JgN7 (you can also easily generate one on your own online)

To run the script, enter this into the command window: python3 web_scraping_requests.py --api_key d6yqmeTangz25ECiWcXaEX0s2VMnMg3zzcZ4JgN7
Format: (python version) web_scraping_requests.py --api_key (API key)

Thank you for taking the time to review this and please let me know if you have any trouble viewing or other questions!

### CODE REVIEW

**Comment by auto-d** [comment]
We checked out and ran the demo successfully! :) 

Feedback on the PR: 
- The purpose of the script is not advertised in the PR text, consider adding a sentence describing the intended behavior and purpose of `web_scraping_requests.py`. 
- I interpreted the failure to identify a PDF as an error, perhaps clarify that this behavior is expected.
    ```
    fetching from https://api.congress.gov/v3/bill/118/hr/7430
    no pdf found for this bill. continuing to next
    fetching from https://api.congress.gov/v3/bill/118/hr/7362
    no pdf found for this bill. continuing to next
    fetching from https://api.congress.gov/v3/bill/118/hres/1028
    no pdf found for this bill. continuing to next
    fetching from https://api.congress.gov/v3/bill/118/hr/7294
    no pdf found for this bill. continuing to next
    fetching from https://api.congress.gov/v3/bill/118/hr/7285
    ```
- The script creates a local directory to store the PDFs it identifies, but the instructions don't call this out. Consider adding an explanation in the script output and/or the PR text. 
- Link to video is using the wrong URL string in the markdown `(url)`... 
- You have great usage info in the script (`python web_scraping_requests.py --help`) but there's no mention of it in the PR text. I had to watch the video to discover this. Maybe add some more info to the PR text to help the TA or other users.

**Comment by recozers** [comment]
Good PR! Having the API key in the command made it very intuitive to run. The 'no pdf found' can seem like an error so more detail about outputs would be good.

**Comment by brinnaebent** [comment]
Video 15/15

**Review by mhy-666 — COMMENTED** [review]
Nice docstrings and clear code structure!

**Pull request merged**
