### PR TITLE
ta1-Kai

### PR DESCRIPTION
**Pull request by K-3016**
Hi,

This is my first submission for team assignment1 via GitHub, api_football.py is to utilize api to get football leagues' information.

A demo video is available in README file.

Thanks for office hours and online tutorials!

### CODE REVIEW

**Comment by brinnaebent** [comment]
@K-3016 please revert changes to the README and requirements.txt in git. Place the text of your README + additional requirements here in your PR. (This helps us avoid merge conflicts!) You should have 1 file changed.

How to revert:

git checkout YOUR_BRANCH_NAME

git checkout data-sourcing-ta1 -- README.md

git add README.md 

git commit -m "Revert changes to README"

git push

**Comment by brinnaebent** [comment]
Video 15/15.

**Comment by K-3016** [comment]
Thanks for your detailed instructions!

Readme file was reverted!

Please feel free to let me know if the anything else I need to provide.

Best regards

**Comment by brinnaebent** [comment]
@K-3016 please also revert requirements.txt (see my instructions above).

**Comment by K-3016** [comment]
Requirements was reverted! Thanks for your patients!

**Pull request merged**
