### PR TITLE
TA5 Dataminers

### PR DESCRIPTION
**Pull request by rajivsraman**
Our slides can be viewed at this link: https://docs.google.com/presentation/d/1NENAg1tU_XTzdS1irr4HU_A9rkSIXSEAtbS9hxKDsOM/edit?usp=sharing. If you'd like us to upload the code we wrote for the app (our creative component), we can push that to our branch as well.

### CODE REVIEW

**Comment by rajivsraman** [comment]
Make sure to include scipy>=1.10.1 as a requirement (not included in the original requirements.txt file).

**Comment by owais-kamdar** [comment]
deployed webpage link: https://one-way-anova-interactive-webpage-idjqygdktcistxcxtfsyvj.streamlit.app/

**Comment by mhy-666** [comment]
Please remove extra files to make sure there is only one file in your PR(which means you can only see one file in the 'files changed' section)

**Comment by rajivsraman** [comment]
> Please remove extra files to make sure there is only one file in your PR(which means you can only see one file in the 'files changed' section)

We removed anovatest.csv, but you need this file to run the code. I am attaching it to this PR comment.

[anovatest.csv](https://github.com/user-attachments/files/17552748/anovatest.csv)

**Comment by mhy-666** [comment]
Nice code, cool! (15/15)

**Pull request merged**
